// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1j4fw5CPEGq9D9N7RE4NrMDZx8byPJYA',
    appId: '1:843803792381:web:2f92e7d540eb3f53fb7f94',
    messagingSenderId: '843803792381',
    projectId: 'prep-294dd',
    authDomain: 'prep-294dd.firebaseapp.com',
    storageBucket: 'prep-294dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_2-bwOXCD7g3pQLNC38M31dvuWeszAgU',
    appId: '1:843803792381:android:ec70191d9690d3eefb7f94',
    messagingSenderId: '843803792381',
    projectId: 'prep-294dd',
    storageBucket: 'prep-294dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhU-0oadoP4iY7EzPFfQL1_5tLQ28Kiw0',
    appId: '1:843803792381:ios:d3bcf5b22b7a645ffb7f94',
    messagingSenderId: '843803792381',
    projectId: 'prep-294dd',
    storageBucket: 'prep-294dd.appspot.com',
    iosBundleId: 'com.example.chordify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhU-0oadoP4iY7EzPFfQL1_5tLQ28Kiw0',
    appId: '1:843803792381:ios:d3bcf5b22b7a645ffb7f94',
    messagingSenderId: '843803792381',
    projectId: 'prep-294dd',
    storageBucket: 'prep-294dd.appspot.com',
    iosBundleId: 'com.example.chordify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1j4fw5CPEGq9D9N7RE4NrMDZx8byPJYA',
    appId: '1:843803792381:web:4ea2be9e8c3aa677fb7f94',
    messagingSenderId: '843803792381',
    projectId: 'prep-294dd',
    authDomain: 'prep-294dd.firebaseapp.com',
    storageBucket: 'prep-294dd.appspot.com',
  );
}
